publish_mode: editorial_workflow
backend:
  name: github
  repo: homedit/thereserve
  base_url: https://9lk3l31h8l.execute-api.us-east-1.amazonaws.com
  auth_endpoint: /prod/auth
  

  
site_id: hugo-lambda-thereserve.s3-website-us-east-1.amazonaws.com
media_folder: "static/uploads" 
public_folder: "/uploads" 
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured image", name: "thumbnail", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list", default: ["news"]}
      - {label: "Tags", name: "tags", widget: "list", default: [""]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "faq" # Used in routes, e.g., /admin/collections/blog
    label: "FAQ" # Used in the UI
    folder: "content/faqs"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured image", name: "thumbnail", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list", default: ["news"]}
      - {label: "Tags", name: "tags", widget: "list", default: ["faq"]}
      - {label: "Body", name: "body", widget: "markdown"}